"""Added profile image

Revision ID: 675be52bee1b
Revises: 662d18460509
Create Date: 2026-06-26 13:02:21.402492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675be52bee1b'
down_revision = '662d18460509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
