"""priority and is_completed coloumn added

Revision ID: 85b6ca838e12
Revises: 770f9e5b4794
Create Date: 2026-05-26 15:08:10.384214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b6ca838e12'
down_revision = '770f9e5b4794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('is_completed')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
