"""add checksum column

Revision ID: 92f8a7a29b4d
Revises: 675be52bee1b
Create Date: 2026-06-30 00:37:20.152589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f8a7a29b4d'
down_revision = '675be52bee1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('checksum')

    # ### end Alembic commands ###
